server:
  port: 9090
  error:
    include-message: always
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
spring:
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: GET, POST, PUT, DELETE
          allowed-headers: "*"
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: labxpert
  datasource:
    url: jdbc:postgresql://localhost:5332/labxpert
    username: postgres
    password: postgres
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.simplon.labxpert: DEBUG
    org.hibernate.SQL: ERROR
  file:
    name: logs/labxpert.log