package com.simplon.labxpert.model.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.simplon.labxpert.model.entity.AnalysisReagent;
import com.simplon.labxpert.model.enums.ReagentStatus;
import lombok.Getter;
import lombok.Setter;

import javax.validation.constraints.*;
import java.time.LocalDateTime;
import java.util.List;

/**
 * DTO for the Reagent entity.
 * It contains all the fields that a reagent can have.
 */
@Getter
@Setter
public class ReagentDTO {

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private long reagentID;

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @Null(message = "reagentSerialNumber is generated by the system")
    private String reagentSerialNumber;

    @NotBlank(message = "reagentName is Mandatory")
    private String reagentName;

    @NotBlank(message = "reagentName is Mandatory")
    private String reagentDescription;

    @NotNull(message = "quantityInStock is Mandatory")
    @Min(value = 0, message = "quantityInStock must be greater than or equal to 0")
    private int quantityInStock;

    @Future(message = "expirationDate must be in the future")
    @NotNull(message = "expirationDate is Mandatory")
    private LocalDateTime expirationDate;

    @NotBlank(message = "supplier is Mandatory")
    private String supplier;

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @Null(message = "reagentStatus is generated by the system")
    private ReagentStatus reagentStatus;
    /*
     * TODO : TO @ayoub ait si ahmad MAKE A JSON VIEW FOR THIS DEPENDING ON THE USE CASE
     * beacause this can cause a mapping error
     * check also if i need it or not
     * private List<AnalysisReagent> analysisReagents;
     */
}
