package com.simplon.labxpert.model.dto;

import com.simplon.labxpert.model.entity.Analysis;
import com.simplon.labxpert.model.entity.Test;
import com.simplon.labxpert.model.enums.ResultStatus;
import lombok.Getter;
import lombok.Setter;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Positive;

@Getter
@Setter
public class TestResultDTO {
    @Positive
    @Null(message = "testId is generated by the system")
    private long testResultID;
    @NotNull(message = "the value of the test is mandatory")
    private double valueOfTest;
    @NotBlank(message = "TestResultStatus is required")
    private ResultStatus testResultStatus;
    @NotNull(message = "Test is mandatory")
    private Test test;
    @NotNull(message = "analysis is mandatory")
    private Analysis analysis;

}
